import type { AttributeDefinition } from './prompts';

export const DEFAULT_ATTRIBUTE_LIBRARY: AttributeDefinition[] = [
  // 大码半身裙
  { category: "大码半身裙", attribute: "品牌", options: ["无品牌"] },
  { category: "大码半身裙", attribute: "色系", options: ["白色系", "灰色系", "黑色系", "红色系", "黄色系", "绿色系", "蓝色系", "紫色系", "棕色"] },
  { category: "大码半身裙", attribute: "尺码类型", options: ["中国码"] },
  { category: "大码半身裙", attribute: "裙型", options: ["T型", "H型", "X型", "A字裙", "O型"] },
  { category: "大码半身裙", attribute: "裙长", options: ["中长裙", "长裙", "超短裙", "短裙"] },
  { category: "大码半身裙", attribute: "腰型", options: ["低腰", "中腰", "高腰"] },
  { category: "大码半身裙", attribute: "闭合方式", options: ["扣式", "系带", "拉链", "松紧带"] },
  { category: "大码半身裙", attribute: "风格", options: ["洛可可风", "文艺风", "华丽风", "优雅风", "极简风", "波西米亚风", "法式", "复古港风", "性感风", "百搭风", "中性风", "田园风", "学院风", "韩式", "民族风", "梦幻风", "街头风", "维多利亚风", "清新风", "摇滚风", "朋克风", "中式", "甜美风", "通勤风", "日系", "牛仔风", "公主风", "欧美风", "嘻哈风", "奢华风", "可爱风", "仙女风", "暗黑风", "运动风", "工装风"] },
  { category: "大码半身裙", attribute: "图案", options: ["斑马纹", "风景", "草莓", "星星", "心形", "波点", "豹纹", "碎花"] },
  { category: "大码半身裙", attribute: "货号", options: [] },
  { category: "大码半身裙", attribute: "厚度", options: ["薄款", "厚款", "常规款"] },
  { category: "大码半身裙", attribute: "适用人群", options: ["成人"] },
  { category: "大码半身裙", attribute: "适用年龄", options: ["18周岁-38周岁"] },
  { category: "大码半身裙", attribute: "适合身材", options: ["O型", "X型"] },
  { category: "大码半身裙", attribute: "组合件数", options: ["单件", "两件套"] },
  { category: "大码半身裙", attribute: "里料材质", options: [] },
  { category: "大码半身裙", attribute: "功能", options: ["显瘦"] },
  { category: "大码半身裙", attribute: "服饰工艺", options: ["刺绣", "不对称", "背带", "立体装饰", "扎花", "乱针修补", "漆皮", "印染", "螺纹"] },
  { category: "大码半身裙", attribute: "辅料材质", options: [] },
  { category: "大码半身裙", attribute: "配料材质成分含量", options: [] },

  // 大码衬衫
  { category: "大码衬衫", attribute: "品牌", options: ["无品牌"] },
  { category: "大码衬衫", attribute: "厚度", options: ["薄款", "厚款", "加绒加厚款"] },
  { category: "大码衬衫", attribute: "服装版型", options: ["宽松型", "修身型"] },
  { category: "大码衬衫", attribute: "货号", options: [] },
  { category: "大码衬衫", attribute: "袖长", options: ["短袖", "九分袖", "五分袖", "无袖", "长袖", "七分袖"] },
  { category: "大码衬衫", attribute: "适用人群", options: [] },
  { category: "大码衬衫", attribute: "适用季节", options: ["夏季", "春季", "冬季", "秋季", "四季通用"] },
  { category: "大码衬衫", attribute: "服饰工艺", options: ["刺绣", "提花", "拼接", "钩花", "镂空", "磨毛", "针织", "做旧"] },
  { category: "大码衬衫", attribute: "领型", options: ["斜领", "高领", "荷叶领", "娃娃领", "围巾领", "半开领", "双层领", "圆领"] },
  { category: "大码衬衫", attribute: "衣长", options: ["常规款", "短款", "中长款", "长款"] },
  { category: "大码衬衫", attribute: "风格", options: ["文艺风", "公主风", "甜美风", "街头风", "性感风", "朋克风", "极简风", "波西米亚风", "暗黑风", "中性风", "二次元风", "韩式", "田园风", "学院风", "嘻哈风", "洛丽塔风", "法式", "欧美风", "民族风", "运动风", "牛仔风", "工装风", "百搭风", "奢华风", "山本风", "可爱风", "优雅风", "慵懒风", "复古港风", "中式", "通勤风", "日式"] },
  { category: "大码衬衫", attribute: "衣门襟", options: ["对襟", "拉链", "三粒扣", "单排两粒扣", "系带", "斜襟", "单排多扣", "开门襟", "套头"] },
  { category: "大码衬衫", attribute: "袖型", options: ["公主袖", "落肩袖", "灯笼袖", "插肩袖", "包袖", "花苞袖", "喇叭袖", "衬衫袖", "牛角袖", "羊腿袖", "蝙蝠袖", "荷叶袖", "花边袖", "花瓣袖", "飞飞袖", "堆堆袖", "泡泡袖", "常规"] },
  { category: "大码衬衫", attribute: "功能", options: ["显瘦", "防晒", "不褪色", "防水", "吸汗", "不起球"] },
  { category: "大码衬衫", attribute: "流行元素", options: ["刺绣", "明线", "镶钻", "3D", "蕾丝", "钉珠", "勾花镂空", "不对称", "锈斑处理"] },
  { category: "大码衬衫", attribute: "里料材质成分含量", options: [] },
  { category: "大码衬衫", attribute: "适用年龄", options: ["18周岁-38周岁"] },
  { category: "大码衬衫", attribute: "组合件数", options: ["单件", "两件套"] },
  { category: "大码衬衫", attribute: "上市时间", options: ["2026年"] },
  { category: "大码衬衫", attribute: "克重", options: [] },

  // 大码裤子
  { category: "大码裤子", attribute: "品牌", options: ["无品牌"] },
  { category: "大码裤子", attribute: "厚度", options: ["薄款", "厚款", "常规款", "加绒加厚款"] },
  { category: "大码裤子", attribute: "裤型", options: ["阔腿裤", "连体裤", "裙裤", "工装裤", "锥形裤", "微喇裤", "运动裤", "小脚裤", "灯笼裤", "铅笔裤", "直筒裤", "束脚裤", "踩脚裤", "喇叭裤", "背带裤", "哈伦裤"] },
  { category: "大码裤子", attribute: "尺码类型", options: ["中国码"] },
  { category: "大码裤子", attribute: "填充物种类", options: ["棉", "白鹅绒", "白鸭绒", "灰鸭绒", "丝棉", "灰鹅绒", "聚酯纤维（涤纶）", "桑蚕丝", "无填充物"] },
  { category: "大码裤子", attribute: "适用人群", options: ["成人"] },
  { category: "大码裤子", attribute: "适用性别", options: ["女"] },
  { category: "大码裤子", attribute: "腰型", options: ["低腰", "中腰", "高腰"] },
  { category: "大码裤子", attribute: "裤长", options: ["中裤", "短裤", "长裤", "九分裤", "八分裤"] },
  { category: "大码裤子", attribute: "风格", options: ["民族风", "性感风", "休闲风", "通勤风", "百搭风", "复古港风", "日系", "极简风", "中国风", "欧美风", "奢华风", "田园风", "韩式", "老钱风"] },
  { category: "大码裤子", attribute: "色系", options: ["白色系", "灰色系", "黑色系", "红色系", "黄色系", "绿色系", "蓝色系", "紫色系", "棕色系"] },
  { category: "大码裤子", attribute: "充绒量", options: [] },
  { category: "大码裤子", attribute: "货号", options: [] },
  { category: "大码裤子", attribute: "弹力", options: ["无弹", "中弹", "高弹", "微弹"] },
  { category: "大码裤子", attribute: "服饰工艺", options: ["磨毛", "针织", "印花", "印染", "拼接", "刺绣", "提花", "做旧"] },
  { category: "大码裤子", attribute: "穿着方式", options: ["不可脱卸内胆", "可脱卸内胆"] },
  { category: "大码裤子", attribute: "里料材质成分含量", options: [] },
  { category: "大码裤子", attribute: "适用年龄", options: ["18周岁-38周岁"] },
  { category: "大码裤子", attribute: "绒子含量", options: [] },
  { category: "大码裤子", attribute: "组合件数", options: ["单件", "两件套"] },
  { category: "大码裤子", attribute: "里料材质", options: [] },
  { category: "大码裤子", attribute: "上市时间", options: ["2026"] },
  { category: "大码裤子", attribute: "克重", options: [] },

  // 大码连衣裙
  { category: "大码连衣裙", attribute: "品牌", options: ["无品牌"] },
  { category: "大码连衣裙", attribute: "领型", options: ["圆领", "POLO领", "V领", "西装领", "荡领", "木耳领", "围巾领", "荷叶领", "连帽", "方领", "娃娃领", "立领", "斜领", "堆堆领", "半开领", "海军领", "一字领", "不规则领", "桃心领"] },
  { category: "大码连衣裙", attribute: "款式", options: ["常规款", "背心", "挂脖", "吊带", "裹胸", "斜肩", "背带款", "连帽"] },
  { category: "大码连衣裙", attribute: "货号", options: [] },
  { category: "大码连衣裙", attribute: "袖长", options: ["短袖", "九分袖", "七分袖", "五分袖", "长袖", "无袖"] },
  { category: "大码连衣裙", attribute: "适用人群", options: ["成人"] },
  { category: "大码连衣裙", attribute: "裙型", options: ["A字裙", "O型", "X型", "H型", "T型", "鱼尾裙", "直筒裙"] },
  { category: "大码连衣裙", attribute: "适用季节", options: ["夏季", "秋季", "春季", "冬季", "四季通用"] },
  { category: "大码连衣裙", attribute: "裙长", options: ["中长裙", "短裙", "超短裙", "长裙"] },
  { category: "大码连衣裙", attribute: "腰型", options: ["高腰", "中腰", "低腰"] },
  { category: "大码连衣裙", attribute: "风格", options: ["极简风", "街头风", "运动风", "百搭风", "工装风", "甜美风", "通勤风", "慵懒风", "波西米亚风", "复古港风", "中性风", "公主风", "嘻哈风", "欧美风", "二次元风", "学院风", "奢华风", "暗黑风", "优雅风", "山本风", "法式", "朋克风", "性感风", "田园风", "可爱风"] },
  { category: "大码连衣裙", attribute: "衣门襟", options: ["牛角扣", "系扣", "拉链", "侧拉链", "斜襟", "系带", "单排多扣", "对襟", "双排扣", "单排两粒扣", "一粒扣", "三粒扣", "单排扣", "暗扣", "开襟", "套头"] },
  { category: "大码连衣裙", attribute: "袖型", options: ["常规", "灯笼袖", "荷叶袖", "泡泡袖", "飞飞袖", "包袖", "公主袖", "露肩", "衬衫袖", "堆堆袖", "蝙蝠袖", "牛角袖", "连袖", "插肩袖", "花瓣袖", "喇叭袖", "蝴蝶袖"] },
  { category: "大码连衣裙", attribute: "里料材质", options: [] },
  { category: "大码连衣裙", attribute: "功能", options: ["不褪色", "高弹力", "吸汗"] },
  { category: "大码连衣裙", attribute: "服饰工艺", options: ["拼接", "绑带", "褶皱", "铆钉", "口袋", "扎花", "蝴蝶结", "螺纹", "镂空"] },
  { category: "大码连衣裙", attribute: "里料材质成分含量", options: [] },
  { category: "大码连衣裙", attribute: "适用年龄", options: ["18-38"] },
  { category: "大码连衣裙", attribute: "组合件数", options: ["假两件", "单件", "两件套"] },
  { category: "大码连衣裙", attribute: "辅料材质", options: [] },
  { category: "大码连衣裙", attribute: "上市时间", options: ["2026"] },

  // 大码毛衣
  { category: "大码毛衣", attribute: "品牌", options: ["无品牌"] },
  { category: "大码毛衣", attribute: "厚度", options: ["薄款", "常规款", "厚款", "加绒加厚款"] },
  { category: "大码毛衣", attribute: "领型", options: ["半高领", "娃娃领", "海军领", "立领", "高领", "连帽", "V领", "低领", "半开领", "双层领", "POLO领", "堆堆领", "圆领", "荷叶领", "方领", "一字领"] },
  { category: "大码毛衣", attribute: "衣长", options: ["短款", "中长款", "长款"] },
  { category: "大码毛衣", attribute: "款式", options: ["高领", "开衫"] },
  { category: "大码毛衣", attribute: "服装版型", options: ["宽松型", "修身型", "标准"] },
  { category: "大码毛衣", attribute: "色系", options: ["白色系", "灰色系", "黑色系", "红色系", "黄色系", "绿色系", "蓝色系", "紫色系", "棕色系"] },
  { category: "大码毛衣", attribute: "尺码类型", options: ["中国码"] },
  { category: "大码毛衣", attribute: "功能", options: ["显瘦"] },
  { category: "大码毛衣", attribute: "货号", options: [] },
  { category: "大码毛衣", attribute: "袖长", options: ["无袖", "短袖", "五分袖", "七分袖", "九分袖", "长袖"] },
  { category: "大码毛衣", attribute: "适用性别", options: ["女"] },
  { category: "大码毛衣", attribute: "服饰工艺", options: ["刺绣", "做旧", "拼接", "镂空", "印花", "染色", "磨毛", "扎染", "针织", "钩花", "毛边", "提花", "压花"] },
  { category: "大码毛衣", attribute: "闭合方式", options: ["单排扣", "双排扣", "牛角扣", "一粒扣", "拉链", "系带", "暗扣"] },
  { category: "大码毛衣", attribute: "毛线粗细", options: ["加粗毛线", "常规毛线 (10针, 12针)", "粗毛线 (8针, 6针)", "细毛线 (16针和14针)"] },
  { category: "大码毛衣", attribute: "风格", options: ["优雅风", "学院风", "北欧风", "中性风", "港风", "街头风", "田园风", "韩式", "民族风", "复古风", "日系", "二次元风", "通勤风", "朋克风", "公主风", "嘻哈风", "欧美风", "文艺风", "甜美风", "传统中国风", "奢华风", "简约风", "可爱风", "暗黑风", "运动风"] },
  { category: "大码毛衣", attribute: "适用年龄", options: ["18周岁-38周岁"] },
  { category: "大码毛衣", attribute: "袖型", options: ["插肩袖", "花瓣袖", "灯笼袖", "公主袖", "衬衫袖", "荷叶袖", "落肩袖", "羊腿袖", "包袖", "泡泡袖", "堆堆袖", "喇叭袖", "飞飞袖", "蝙蝠袖"] },
  { category: "大码毛衣", attribute: "组合件数", options: ["单件", "两件套"] },
  { category: "大码毛衣", attribute: "流行元素", options: ["拼接", "褶皱", "螺纹", "扎花", "立体装饰", "不对称", "植绒", "荷叶边"] },
  { category: "大码毛衣", attribute: "图案", options: ["菱形", "圆点", "格子", "蝴蝶结", "卡通动漫", "骷髅头", "熊", "猫咪"] },
  { category: "大码毛衣", attribute: "上市时间", options: ["2026"] },

  // 大码牛仔裤
  { category: "大码牛仔裤", attribute: "品牌", options: ["无品牌"] },
  { category: "大码牛仔裤", attribute: "厚度", options: ["薄款", "厚款", "加绒加厚款"] },
  { category: "大码牛仔裤", attribute: "裤型", options: ["阔腿裤", "连体裤", "喇叭裤", "铅笔裤", "直筒裤", "哈伦裤", "背带裤", "灯笼裤", "微喇裤", "小脚裤", "弯刀裤", "烟管裤", "束脚裤"] },
  { category: "大码牛仔裤", attribute: "服饰工艺", options: ["刺绣", "印染", "印花", "磨白", "磨破", "翻边", "做旧", "褶皱"] },
  { category: "大码牛仔裤", attribute: "货号", options: [] },
  { category: "大码牛仔裤", attribute: "弹力", options: ["微弹", "高弹", "无弹", "中弹"] },
  { category: "大码牛仔裤", attribute: "适用季节", options: ["夏季"] },
  { category: "大码牛仔裤", attribute: "颜色", options: ["紫色", "黑色", "白色", "蓝色", "红色", "咖色", "迷彩色", "卡其色", "豹纹"] },
  { category: "大码牛仔裤", attribute: "适用性别", options: ["女"] },
  { category: "大码牛仔裤", attribute: "腰型", options: ["高腰", "低腰", "中腰"] },
  { category: "大码牛仔裤", attribute: "裤长", options: ["九分裤", "八分裤", "七分裤", "长裤", "中裤", "六分裤", "短裤"] },
  { category: "大码牛仔裤", attribute: "风格", options: ["极简风", "清新风", "日系", "INS风", "性感风", "韩式", "田园风", "休闲风", "法式", "甜美风", "复古港风", "运动风", "英伦风", "学院风", "民族风", "嘻哈风", "中式"] },
  { category: "大码牛仔裤", attribute: "适用年龄", options: ["18-38"] },
  { category: "大码牛仔裤", attribute: "组合件数", options: ["假两件", "单件", "两件套"] },
  { category: "大码牛仔裤", attribute: "上市时间", options: ["2026"] },

  // 时尚套装
  { category: "时尚套装", attribute: "品牌", options: ["无品牌"] },
  { category: "时尚套装", attribute: "货号", options: [] },
  { category: "时尚套装", attribute: "组合件数", options: ["单件", "三件", "两件", "4件套"] },
  { category: "时尚套装", attribute: "适用年龄", options: ["18周岁-38周岁"] },
  { category: "时尚套装", attribute: "风格", options: ["简约风", "中国风", "日式", "森系", "INS风", "东南亚风", "原宿风", "宫廷风"] },

  // 大码T恤
  { category: "大码T恤", attribute: "品牌", options: ["无品牌"] },
  { category: "大码T恤", attribute: "服装版型", options: ["宽松型", "修身型", "标准"] },
  { category: "大码T恤", attribute: "袖长", options: ["短袖", "无袖", "五分袖", "七分袖", "九分袖", "长袖"] },
  { category: "大码T恤", attribute: "适用性别", options: ["女"] },
  { category: "大码T恤", attribute: "领型", options: ["连帽", "半高领", "U型领", "V领", "双层领", "西装领", "POLO领", "娃娃领", "荷叶领", "立领", "一字领", "方领", "圆领", "半开领", "堆堆领", "围巾领", "海军领", "斜领"] },
  { category: "大码T恤", attribute: "衣长", options: ["中长款", "短款", "常规款", "长款"] },
  { category: "大码T恤", attribute: "风格", options: ["中性风", "民族风", "复古港风", "中式", "通勤风", "日系", "二次元风", "公主风", "文艺风", "欧美风", "学院风", "可爱风", "甜美风", "仙女风", "暗黑风", "运动风", "极简风", "性感风", "街头风", "韩式"] },
  { category: "大码T恤", attribute: "货号", options: [] },
  { category: "大码T恤", attribute: "服饰工艺", options: ["印花", "贴布绣", "镂空", "烫印", "拼接", "刺绣/绣花", "染色", "烫钻", "刺绣"] },
  { category: "大码T恤", attribute: "适用年龄", options: ["18周岁-38周岁"] },
  { category: "大码T恤", attribute: "袖型", options: ["灯笼袖", "喇叭袖", "飞飞袖", "荷叶袖", "堆堆袖", "落肩袖", "包袖", "蝙蝠袖", "衬衫袖", "插肩袖", "泡泡袖", "牛角袖", "花瓣袖", "常规", "公主袖"] },
  { category: "大码T恤", attribute: "图案文化", options: ["魔幻", "童话", "青春", "电影", "文艺", "幽默", "节庆", "经典", "亲情", "爱情", "搞怪", "科幻"] },
  { category: "大码T恤", attribute: "功能", options: ["抗静电", "速干", "不起球", "抗皱", "不褪色", "透气", "显瘦"] },
  { category: "大码T恤", attribute: "流行元素", options: ["纱网", "露背", "系带", "立体装饰", "镶钻", "破洞", "燕尾", "流苏", "刺绣"] },
  { category: "大码T恤", attribute: "图案", options: ["脸谱", "人物", "建筑", "风景", "数字", "字母", "几何图案", "植物花卉"] },
  { category: "大码T恤", attribute: "上市时间", options: ["2026年"] },
  { category: "大码T恤", attribute: "克重", options: [] }
];

export function attributesForCategory(category: string): AttributeDefinition[] {
  const normalized = category.trim();
  return DEFAULT_ATTRIBUTE_LIBRARY.filter((item) => item.category === normalized);
}
